function axes1 = createfigure(X1, Y1, xLabel, yLabel, axes1)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 02-Dec-2010 14:34:49

% Create figure

if nargin == 4
    figure1 = figure;
    % Create axes
    axes1 = axes('Parent',figure1);
end


box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1);

% Create xlabel
xlabel({xLabel});

% Create ylabel
ylabel({yLabel});
